# Generated by Django 5.0.6 on 2024-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cthd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, db_column='SL', null=True)),
            ],
            options={
                'db_table': 'CTHD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('sohd', models.IntegerField(db_column='SOHD', primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField(blank=True, db_column='NGHD', null=True)),
                ('trigia', models.DecimalField(blank=True, db_column='TRIGIA', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'HOADON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makh', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MAKH', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('dchi', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DCHI', max_length=50, null=True)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngsinh', models.DateTimeField(blank=True, db_column='NGSINH', null=True)),
                ('doanhso', models.DecimalField(blank=True, db_column='DOANHSO', decimal_places=4, max_digits=19, null=True)),
                ('ngdk', models.DateTimeField(blank=True, db_column='NGDK', null=True)),
                ('loaikh', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='LOAIKH', max_length=20, null=True)),
            ],
            options={
                'db_table': 'KHACHHANG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manv', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MANV', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngvl', models.DateTimeField(blank=True, db_column='NGVL', null=True)),
            ],
            options={
                'db_table': 'NHANVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('masp', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MASP', max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='TENSP', max_length=40, null=True)),
                ('dvt', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DVT', max_length=20, null=True)),
                ('nuocsx', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='NUOCSX', max_length=40, null=True)),
                ('gia', models.DecimalField(blank=True, db_column='GIA', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'SANPHAM',
                'managed': False,
            },
        ),
    ]
