# Generated by Django 5.0.6 on 2024-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manv', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MANV', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngvl', models.DateTimeField(blank=True, db_column='NGVL', null=True)),
            ],
            options={
                'db_table': 'NHANVIEN',
                'managed': False,
            },
        ),
    ]
