# Generated by Django 5.0.6 on 2024-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('masp', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MASP', max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='TENSP', max_length=40, null=True)),
                ('dvt', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DVT', max_length=20, null=True)),
                ('nuocsx', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='NUOCSX', max_length=40, null=True)),
                ('gia', models.DecimalField(blank=True, db_column='GIA', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'SANPHAM',
                'managed': False,
            },
        ),
    ]
