# Generated by Django 5.0.6 on 2024-05-12 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makh', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=40)),
                ('dchi', models.CharField(max_length=50, null=True)),
                ('sodt', models.CharField(max_length=20)),
                ('ngsinh', models.DateTimeField(null=True)),
                ('doanhso', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ngdk', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('manv', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=40)),
                ('sodt', models.CharField(max_length=20)),
                ('ngvl', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('masp', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=40)),
                ('dvt', models.CharField(choices=[('cay', 'Cay'), ('hop', 'Hop'), ('cai', 'Cai'), ('quyen', 'Quyen'), ('chuc', 'Chuc')], max_length=20)),
                ('nuocsx', models.CharField(max_length=40)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(500)])),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('sohd', models.IntegerField(primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField()),
                ('trigia', models.DecimalField(decimal_places=2, max_digits=19)),
                ('makh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.khachhang')),
                ('manv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='CTHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sohd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.hoadon')),
                ('masp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.sanpham')),
            ],
        ),
    ]
