# Generated by Django 5.0.6 on 2024-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlbh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Vietnamese_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Vietnamese_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Vietnamese_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Vietnamese_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Vietnamese_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Vietnamese_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makh', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MAKH', max_length=4)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('dchi', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DCHI', max_length=50, null=True)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngsinh', models.DateTimeField(blank=True, db_column='NGSINH', null=True)),
                ('doanhso', models.DecimalField(blank=True, db_column='DOANHSO', decimal_places=4, max_digits=19, null=True)),
                ('ngdk', models.DateTimeField(blank=True, db_column='NGDK', null=True)),
                ('loaikh', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='LOAIKH', max_length=20, null=True)),
            ],
            options={
                'db_table': 'KHACHHANG1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QlbhCthd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sl', models.IntegerField()),
            ],
            options={
                'db_table': 'qlbh_cthd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QlbhHoadon',
            fields=[
                ('sohd', models.IntegerField(primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField()),
                ('trigia', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'qlbh_hoadon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QlbhKhachhang',
            fields=[
                ('makh', models.CharField(db_collation='Vietnamese_CI_AS', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40)),
                ('dchi', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', max_length=20)),
                ('ngsinh', models.DateTimeField(blank=True, null=True)),
                ('doanhso', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ngdk', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qlbh_khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QlbhNhanvien',
            fields=[
                ('manv', models.CharField(db_collation='Vietnamese_CI_AS', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', max_length=20)),
                ('ngvl', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qlbh_nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QlbhSanpham',
            fields=[
                ('masp', models.CharField(db_collation='Vietnamese_CI_AS', max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40)),
                ('dvt', models.CharField(db_collation='Vietnamese_CI_AS', max_length=20)),
                ('nuocsx', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'qlbh_sanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masp', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MASP', max_length=4)),
                ('tensp', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='TENSP', max_length=40, null=True)),
                ('dvt', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DVT', max_length=20, null=True)),
                ('nuocsx', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='NUOCSX', max_length=40, null=True)),
                ('gia', models.DecimalField(blank=True, db_column='GIA', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'SANPHAM1',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cthd',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='khachhang',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'managed': False},
        ),
    ]
