# Generated by Django 5.0.6 on 2024-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makh', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MAKH', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('dchi', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='DCHI', max_length=50, null=True)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngsinh', models.DateTimeField(blank=True, db_column='NGSINH', null=True)),
                ('doanhso', models.DecimalField(blank=True, db_column='DOANHSO', decimal_places=4, max_digits=19, null=True)),
                ('ngdk', models.DateTimeField(blank=True, db_column='NGDK', null=True)),
                ('loaikh', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', db_column='LOAIKH', max_length=20, null=True)),
            ],
            options={
                'db_table': 'KHACHHANG',
                'managed': False,
            },
        ),
    ]
