# Generated by Django 5.0.6 on 2024-06-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khachhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cthd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(db_column='SL')),
            ],
            options={
                'db_table': 'CTHD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('sohd', models.IntegerField(db_column='SOHD', primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField(db_column='NGHD')),
                ('trigia', models.DecimalField(db_column='TRIGIA', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'HOADON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manv', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MANV', max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_collation='Vietnamese_CI_AS', db_column='HOTEN', max_length=40)),
                ('sodt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='SODT', max_length=20)),
                ('ngvl', models.DateTimeField(db_column='NGVL')),
            ],
            options={
                'db_table': 'NHANVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('masp', models.CharField(db_collation='Vietnamese_CI_AS', db_column='MASP', max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(db_collation='Vietnamese_CI_AS', db_column='TENSP', max_length=40)),
                ('dvt', models.CharField(db_collation='Vietnamese_CI_AS', db_column='DVT', max_length=20)),
                ('nuocsx', models.CharField(db_collation='Vietnamese_CI_AS', db_column='NUOCSX', max_length=40)),
                ('gia', models.DecimalField(db_column='GIA', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'SANPHAM',
                'managed': False,
            },
        ),
    ]
